object Dependencies {
    val kotlin = "org.jetbrains.kotlin:kotlin-stdlib-jdk7:${Versions.kotlinVersion}"
    val appcompat = "androidx.appcompat:appcompat:${Versions.appcompatVersion}"
    val ktxCore = "1.0.1"
    val junit =  "junit:junit:${Versions.junitVersion}"
    val androidxTestRunner =  "androidx.test:runner:${Versions.androidxTestRunnerVersion}"
    val espressoCore = "androidx.test.espresso:espresso-core:${Versions.espressoCoreVersion}"
    val dagger = "com.google.dagger:dagger:${Versions.daggerVersion}"
    val daggerAndroid = "com.google.dagger:dagger-android-support:${Versions.daggerVersion}"
    val daggerCompiler = "com.google.dagger:dagger-compiler:${Versions.daggerVersion}"
    val daggerProcessor = "com.google.dagger:dagger-android-processor:${Versions.daggerVersion}"
    val lifecycleExtension = "androidx.lifecycle:lifecycle-extensions:${Versions.lifecycleVersion}"
    val lifecycleViewModel = "androidx.lifecycle:lifecycle-viewmodel-ktx:${Versions.lifecycleVersion}"
    val lifecycleCompiler = "androidx.lifecycle:lifecycle-compiler:${Versions.lifecycleVersion}"
    val retrofit = "com.squareup.retrofit2:retrofit:${Versions.retrofitVersion}"
    val retrofitGsonConverter = "com.squareup.retrofit2:converter-gson:${Versions.retrofitVersion}"
    val retrofitRxJavaAdapter = "com.squareup.retrofit2:adapter-rxjava2:${Versions.retrofitVersion}"
    val okhttp = "com.squareup.okhttp3:logging-interceptor:${Versions.okhttpVersion}"
    val recyclerView = "androidx.recyclerview:recyclerview:${Versions.recyclerViewVersion}"
    val cardView = "1.0.0"
    val rxAndroid = "io.reactivex.rxjava2:rxandroid:${Versions.rxAndroidVersion}"
    val rxJava = "io.reactivex.rxjava2:rxjava:${Versions.rxJavaVersion}"
    val glide = "com.github.bumptech.glide:glide:${Versions.glideVersion}"
    val glideCompiler = "com.github.bumptech.glide:compiler:${Versions.glideVersion}"
    val truth =  "com.google.truth:truth:${Versions.truthVersion}"
    val truthExt = "androidx.test.ext:truth:${Versions.truthExtVersion}"
    val mockK = "io.mockk:mockk:${Versions.mockKVersion}"
    val orchestrator = "1.1.1"
    val coreTesting = "androidx.arch.core:core-testing:${Versions.coreTestingVersion}"
    val material = "com.google.android.material:material:${Versions.materialVersion}"
    val roomRuntime = "androidx.room:room-runtime:${Versions.roomVersion}"
    val roomCompiler = "androidx.room:room-compiler:${Versions.roomVersion}"
    val roomKtx = "androidx.room:room-ktx:${Versions.roomVersion}"
    val roomRxJava = "androidx.room:room-rxjava2:${Versions.roomVersion}"

}