object Versions {
    const val kotlinVersion = "1.3.72"
    const val gradleVersion = "4.0.0-rc01"
    const val appcompatVersion = "1.3.0-alpha01"
    const val junitVersion = "4.13"
    const val androidxTestRunnerVersion = "1.3.0-beta02"
    const val espressoCoreVersion = "3.3.0-beta02"
    const val daggerVersion = "2.27"
    const val retrofitVersion = "2.9.0"
    const val okhttpVersion = "4.7.2"
    const val recyclerViewVersion = "1.2.0-alpha03"
    const val rxAndroidVersion = "3.0.0"
    const val rxJavaVersion = "3.0.3"
    const val glideVersion = "4.11.0"
    const val truthExtVersion = "1.3.0-beta02"
    const val mockKVersion = "1.10.0"
    const val coreTestingVersion = "2.1.0"
    const val materialVersion = "1.2.0-alpha06"
    const val gradleVersionPluginVersion = "0.28.0"
}